[build]
  publish = ".vitepress/dist"
  command = "npm run docs:build"

[build.environment]
  NODE_VERSION = "18"

# 重定向和自定义头信息
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    Cache-Control = "public, max-age=86400"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block" 